apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        node-type: "karpenter"
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In  
          values: ["t3.medium", "t3.large", "c5.large", "m5.large"]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
  limits:
    cpu: 1000
    memory: 1000Gi
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  instanceProfile: "KarpenterNodeInstanceProfile-eks-lab-test-eks"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-lab-test-eks"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-lab-test-eks"
  amiFamily: AL2023
  userData: |
    #!/bin/bash
    /etc/eks/bootstrap.sh eks-lab-test-eks