# ArgoCD Helm Values
# Author: jasontsai
# Repository: https://github.com/jasontsaicc/eks-terraform-karpenter

global:
  domain: argocd.example.com
  
configs:
  params:
    server.insecure: false
    server.disable.auth: false
    
  cm:
    url: https://argocd.example.com
    application.instanceLabelKey: argocd.argoproj.io/instance
    exec.enabled: true
    admin.enabled: true
    timeout.reconciliation: 180s
    timeout.hard.reconciliation: 0s
    
  secret:
    createSecret: true
    argocdServerAdminPassword: "$2a$10$rRGqHrA7Y5A5Z7hKF0Yd4uV5JhuLxLVfmMpP8aXnwDWQgD.u0XW9i" # changeme

server:
  replicas: 2
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
    
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
      
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-1:ACCOUNT_ID:certificate/CERT_ID"
    hosts:
      - argocd.example.com
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.example.com
          
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      
controller:
  replicas: 2
  
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
      
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      
repoServer:
  replicas: 2
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
    
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi
      
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      
applicationSet:
  enabled: true
  replicas: 2
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
      
notifications:
  enabled: true
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
      
redis:
  enabled: true
  
  ha:
    enabled: true
    
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
      
dex:
  enabled: false  # 使用外部 OIDC 提供者時啟用