apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  # AMI 配置
  amiFamily: AL2
  amiSelectorTerms:
    - alias: al2@latest
  
  # 實例配置
  associatePublicIPAddress: false
  instanceStorePolicy: RAID0
  
  # IAM 配置
  role: KarpenterNodeRole-eks-lab-test-eks
  
  # 網路配置
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-lab-test-eks
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-lab-test-eks
  
  # 簡化 IMDS 配置
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional  # 暫時改為 optional 以排除 IMDS token 問題
  
  # 最簡化但包含必要參數的 User Data
  userData: |
    #!/bin/bash
    /etc/eks/bootstrap.sh eks-lab-test-eks \
      --container-runtime containerd \
      --apiserver-endpoint https://3F1AA6C6B518B869FDDAFD647F3DEFB4.sk1.ap-southeast-1.eks.amazonaws.com \
      --b64-cluster-ca LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSStqUWM5ZkRnSGt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNE1qVXhNakF5TWpSYUZ3MHpOVEE0TWpNeE1qQTNNalJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNxUDVmaTRIM1c2TDBBUVNBeDR4Mjl6UzZieTI5YWFBZlEzUXdoaVA0OGNST2ZOb3JrTkJjckdVY2kKY2dGMjgvTy81bm53UmtKRWhWUmg2R2JVdCtUSk5OUXVYbDc3bWVPSVBTNVQyQWd6Q0JmMnFESTFQeVVBVW9tSgp1K3d4Qm5razgreVJYM1R1blQ2d2xxc01tc1hvU2xib2VaeXhFWXBCbFZIdWkvZWs0ZUxtZUd6V2J0OUN0QnJYCjVqc3NBOTV2NnI4VHExZEpabzQ5UHdFbmFlQWhDRTJDYlpHS0oxM1dKK3RzcDRvaTVycnJEN2dOMk5FVndHWUQKK0ZZN2RXTnJ0QTlZL0krMnJVYmFLUlA1WUlJV2RKUlZKcG1oOHBVdExxOG9sRk1CdjhEQjUyK0Ewb3VZUXNibQpobTdCenQ2QkVta3RGcmpUd2w3MEhobERUTktmQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRYkl0VUpyNVh2NTlFMythRWN1VHBTcTVBMDdEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkowZ3lUb2NaTgp6dmVoNm01Z2hXU2hzS1pnVkdoNXBoSU0yclZMaWpMc2c5R0hJckxNdUxHYi8zTVdNUHMrekxhK3dOL2k3ZmtpCjNEQ2ROT1M1eXFaVTNGMnZCT0tUdmdHTkxEOXJlSlJuaXZ6VGlUTGtoNFJFOFh2SHlnRnpHeFZSMmlKNmZJYWcKaUVWN0xYbE1haGdZMWVvUkxCM3Y0ZE9ycnZKTCthSUg1aGRPTkl4WkRCd1Z5WWZOMk9iMElXMFZKMTAxelUraAp6bVJBcnp6TktWWUdqK2NBVk9DaXZrS0Qrd2swcndNUnZuMmZCLzlya2JMdzRjSkRQeXZ6cThTWjBTUVlyQmo1CkovcktTMElkcFUvZkJ0azFhSGg1UWlLcStGUmczRkpYWGhESEt4U1QvbW05SFk5MVhKMWdta1dqNEs1T2ptOU4Kb3lJRDU3b3FFTHJNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K