apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: nginx-test
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
